name: CI/CD

on:
    push:
        branches:
            - '*' 
    pull_request:
        branches:
            - '*' 

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20' # node.js version

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                      libgtk-3-dev \
                      libgdk-pixbuf2.0-dev \
                      libglib2.0-dev \
                      libjavascriptcoregtk-4.0-dev \
                      libwebkit2gtk-4.1-dev \
                      libappindicator3-dev \
                      librsvg2-dev patchelf

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Deploy
              run: |
                  echo "Deploying to production..."
                  pnpm tauri build
